services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: npm run start-backend
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri
      - key: SECRET
        value: your_secret
      - key: SESSION_SECRET
        value: your_session_secret

  - type: web
    name: frontend
    env: node
    buildCommand: npm install && npm run build-frontend
    startCommand: npm run start-frontend
